apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/baremetal/deploy.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-nginx-controller
  path: overlays/production/ingress-nginx-controller-deployment-patch.yaml
- path: overlays/production/ingress-nginx-controller-service.yaml